// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class SelectionControllerEventArgs : EventArgs
{
  public System.DateTime EventTime;

  public ControllerType Device;

  public bool Conflict = false;

  public SelectionControllerEventArgs()
  {
    EventTime = System.DateTime.Now;
    Device = ControllerType.TouchPad;
  }

  public TimeSpan TimeEllapsed()
  {
    return System.DateTime.Now - EventTime;
  }
}

