// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace UnityMoverioBT200.Scripts
{

  public enum MoverioInputEventType { TouchStarted, TouchEnded, TouchMoved, Tap, DoubleTap }

  public class MoverioInputEventArgs : EventArgs
  {
    public Vector2 Position;
    public Vector2 Origin; //first position in this chain of events
    public Vector2 Last; //position in the last frame

    public Vector2 DragFromOrigin;
    public Vector2 DragFromLast;

    public System.DateTime EventTime = System.DateTime.MinValue;
    public System.TimeSpan Duration = System.TimeSpan.MaxValue;

    public MoverioInputEventType Type;

    public MoverioInputEventArgs(MoverioInputEventType type)
    {
      EventTime = System.DateTime.Now;
      Type = type;
    }

    public MoverioInputEventArgs Prepare()
    {
      DragFromLast = Position - Last;
      DragFromOrigin = Position - Origin;

      return this;
    }
  }

}