// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace UnityMoverioBT200.Scripts
{
	public enum ReferenceFrame { View, Body, World }

	//The scene script is responsible for setting this enviroment variable and broadcasting the event
	// void OnReferenceFrameUpdated(ReferenceFrame rf)
}

