// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace UnityMoverioBT200.Scripts
{

  public class SelectionControllerEventArgs : EventArgs
  {
    public System.DateTime EventTime;
    public ControllerType Device;
    public bool Conflict = false;

    public MoverioInputEventArgs MoverioEvent;
    public Vector3 Pointer;

    public SelectionControllerEventArgs(MoverioInputEventArgs mieArgs)
    {
      EventTime = System.DateTime.Now;
      Device = ControllerType.TouchPad;
      MoverioEvent = mieArgs;

      if (MoverioEvent != null)
        Pointer = MoverioEvent.Type == MoverioInputEventType.TouchStarted ? MoverioEvent.Origin : MoverioEvent.Last;
    }

    public TimeSpan TimeEllapsed()
    {
      return System.DateTime.Now - EventTime;
    }
  }


}