// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class MoverioInputEventArgs : EventArgs
{
  public Vector2 Position;
  public Vector2 Origin; //first position in this chain of events
  public Vector2 Last; //position in the last frame

  public Vector2 DragFromOrigin;
  public Vector2 DragFromLast;

  public System.DateTime EventTime = System.DateTime.MinValue;
  public System.TimeSpan EventLenght = System.TimeSpan.MaxValue;

  public MoverioInputEventArgs()
  {
    EventTime = System.DateTime.Now;
  }

  public MoverioInputEventArgs Prepare()
  {
    DragFromLast = Position - Last;
    DragFromOrigin = Position - Origin;

    return this;
  }
}

